In [2]:
import numpy as np
import cv2
import os
import json

def create2DArray(start_val, end_val):
    chess_2d_array = []
    val = np.arange(start_val,end_val)
    for a in val:
        for b in val:
            chess_2d_array.append([a,b])
    return chess_2d_array

#corners: quello che ti dà la findChessboardCorners
def saveToJSON(dict, camera_number):
    with open(f"{camera_number}Fcorners.json", "a+") as outfile:
        json.dump(dict, outfile)
        return True
    return False

In [3]:
camera_number = 1
frame_count = 0
image_number = 10

#print(os.listdir())

abs_dir_path = "videos/"
VIDEO_NAME = f'out{camera_number}F.mp4'
ROW_POINTS = 5
COLUMNS_POINTS = 7
# Open the video file 
video_capture = cv2.VideoCapture(filename=f'{abs_dir_path}{VIDEO_NAME}')

# Print the number of frames in the video
number_of_frame = int(video_capture.get(cv2.CAP_PROP_FRAME_COUNT))
print("Number of frames in the video: ", number_of_frame)

Number of frames in the video:  2584


In [4]:
os.listdir()
#os.chdir('..')

['videos',
 'README.md',
 '__pycache__',
 'Calibration.pdf',
 'CVprojects-Sport.pdf',
 'Rizzetto-Tomaselli_Report.pdf',
 '.git',
 'chessboard_calibration.py',
 'Accuracy_Evaluation_and_Prediction_of_Single-Image_Camera_Calibration.pdf',
 'LICENSE',
 'samples',
 'report',
 '.gitignore',
 'lib',
 'checkboard_test.ipynb',
 'appunti']

In [5]:
# Create a directory to save the screen captures named as the video file
output_dir = 'samples/' + f'out{camera_number}'
os.makedirs(output_dir, exist_ok=True)
print("Saving frames to ", output_dir)
# Remove all files in the directory
for file in os.listdir(output_dir):
    os.remove(os.path.join(output_dir, file))


Saving frames to  samples/out1


In [10]:
import lib.util as util
import lib.Calibration as cal
import re

camera_number = '1F'
relative_path = "videos/"
VIDEO_NAME = f'out{camera_number}.mp4'
video_path = f'{relative_path}{VIDEO_NAME}'

all_chessboard_sizes = [(5, 7), (5, 7), (5, 7), (5, 7), (6, 9), (6, 9), (5, 7), (6, 9), (6, 9), (0, 0), (6, 9), (5, 7),
                        (5, 7)]

chessboard_size = all_chessboard_sizes[int(re.search("\d*", camera_number)[0]) - 1]

CHESS_WIDTH = chessboard_size[0]
CHESS_HEIGHT = chessboard_size[1]

v8F = cal.Calibration(video_path, CHESS_WIDTH, CHESS_HEIGHT)
print(v8F.total_frame_number)
imgpoints = v8F.fastCalibrationImageSearch(output_dir= output_dir, skip_step=40, batch_size=3)

#util.saveToJSON({[f'{camera_number}',imgpoints]}, 8)

2584
[[1076.1283 1501.6351]]
saving images to directory
find one: 320
[[1089.1387 1504.2208]]
saving images to directory
find one: 520
[[1119.1309 1443.2417]]
saving images to directory
find one: 560
starting big skip of 103: 561
frame after skip: 664
[[2008.4825 1250.705 ]]
saving images to directory
find one: 680
[[2482.6428 1233.6948]]
saving images to directory
find one: 720
[[3071.4585 1228.5383]]
saving images to directory
find one: 760
starting big skip of 103: 761
frame after skip: 864
[[2271.5632 1109.9219]]
saving images to directory
find one: 880
[[1495.9291 1114.7991]]
saving images to directory
find one: 920
[[ 722.8061 1127.9891]]
saving images to directory
find one: 960
starting big skip of 103: 961
frame after skip: 1064
[[605.68994 911.14655]]
saving images to directory
find one: 1080
[[1249.2875  735.8589]]
saving images to directory
find one: 1120
[[1602.1794  711.8434]]
saving images to directory
find one: 1160
starting big skip of 103: 1161
frame after skip: 1264
[

In [11]:
import datetime as dt
#findChessboard Flag test
one = cal.Calibration(video_path, CHESS_WIDTH, CHESS_HEIGHT)
skip = 500
img = []
print(f'starting skip of {skip}')
for i in range(skip):
    ret, img = one.video_capture.read()
    if not ret:
        break
print(f'frame after skip')

cv2.namedWindow("test image", cv2.WINDOW_NORMAL) 
  
# Using resizeWindow() 
cv2.resizeWindow("test image", 1920, 1080) 
  
# Displaying the image 
cv2.imshow("test image", img) 

one.video_capture.release()
cv2.waitKey(0)
cv2.destroyAllWindows()

#flags FAST_CHECK -> False FAST_CHECK + NORMALIZE -> False  None -> True FAST_CHECK + NORMALIZE + THRESH 
now = dt.datetime.now()
timestamp = util.getSeconds(now)
ret, imgpoints = one.extractCorners(img= img, output_dir= 'test/', find_flags=  cv2.CALIB_CB_ADAPTIVE_THRESH + cv2.CALIB_CB_NORMALIZE_IMAGE + cv2.CALIB_CB_FAST_CHECK)
now = dt.datetime.now()
t2 = util.getSeconds(now)
print(f"all flags time: {(t2 - timestamp)}")
print(ret)

now = dt.datetime.now()
timestamp = util.getSeconds(now)
ret, imgpoints = one.extractCorners(img= img, output_dir= 'test/', find_flags=  None)
now = dt.datetime.now()
t2 = util.getSeconds(now)
print(f"no flags time: {(t2 - timestamp)}")
print(ret)

now = dt.datetime.now()
timestamp = util.getSeconds(now)
ret, imgpoints = one.extractCorners(img= img, output_dir= 'test/', find_flags=  cv2.CALIB_CB_ADAPTIVE_THRESH + cv2.CALIB_CB_FAST_CHECK)
now = dt.datetime.now()
t2 = util.getSeconds(now)
print(f"no fast flag time: {(t2 - timestamp)}")
print(ret)


starting skip of 500
frame after skip
[[ 581.54016 1488.0059 ]]
saving images to directory
all flags time: 228498
True
[[ 581.54016 1488.0059 ]]
saving images to directory
no flags time: -481
True
[[ 580.76636 1487.8502 ]]
saving images to directory
no fast flag time: 14300
True


In [ ]:
#objpoints search


In [10]:
##JSON TEST
frame_skip = 10
for i in range(1400):
    ret, img = video_capture.read()

json_dict = {}

while True:
        # Read a frame from the video
        ret, img = video_capture.read()
        if not ret:
            break  # Break the loop if we've reached the end of the video

        # Skip frames based on the frame_skip value
        if frame_count % frame_skip == 0 :
            # Resize the frame to the new_resolution
            real_img = img
            
            gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
            #corners = []
            # Find the chessboard corners
            found_corners, corners = cv2.findChessboardCorners(gray, (ROW_POINTS, COLUMNS_POINTS), corners= None)
            #res_img = cv2.drawChessboardCorners(img,(ROW_POINTS,COLUMNS_POINTS),corners,found_corners)
            if found_corners:
                #populating the dictionary with the points
                print('saving to JSON')
                json_dict.update([[f"{camera_number}_{1000 + frame_count}" , corners.tolist()]])
            print(frame_count)
        
            #print("Frame ", frame_count, ":", found_corners)
            #res_img = cv2.cvtColor(res_img, cv2.COLOR_GRAY2BGR)
        frame_count += 1  
        if frame_count == 300:
            break  

res = saveToJSON(json_dict, camera_number)
print(res)

0
10
20
30
40
50
60
70
80
90
100
110
120
130
saving to JSON
140
150
160
170
180
190
200
210
220
saving to JSON
230
240
250
260
270
280
290
True


In [22]:
saveToJSON(np.array([[12,3],[3,3]]),1,210)
saveToJSON(np.array([[12,3],[3,3]]),2,100)
