In [ ]:
import numpy as np
import cv2
import os

In [ ]:
camera_number = 1
frame_count = 0
image_number = 10

#print(os.listdir())

abs_dir_path = "videos/"
VIDEO_NAME = f'out{camera_number}F.mp4'
ROW_POINTS = 5
COLUMNS_POINTS = 7
# Open the video file 
video_capture = cv2.VideoCapture(filename=f'{abs_dir_path}{VIDEO_NAME}')

# Print the number of frames in the video
number_of_frame = int(video_capture.get(cv2.CAP_PROP_FRAME_COUNT))
print("Number of frames in the video: ", number_of_frame)

In [ ]:
os.listdir()
#os.chdir('..')

In [ ]:
# Create a directory to save the screen captures named as the video file
output_dir = 'samples/' + f'out{camera_number}'
os.makedirs(output_dir, exist_ok=True)
print("Saving frames to ", output_dir)
# Remove all files in the directory
for file in os.listdir(output_dir):
    os.remove(os.path.join(output_dir, file))


In [ ]:
#findChessboard Flag test
import datetime as dt
import lib.util as util
import lib.Calibration as cal
import cv2 

video_path = '...'
width = 0
height = 0

one = cal.Calibration(video_path, width, height)
skip = 500
img = []
print(f'starting skip of {skip}')
for i in range(skip):
    ret, img = one.video_capture.read()
    if not ret:
        break
print(f'frame after skip')

cv2.namedWindow("test image", cv2.WINDOW_NORMAL) 
  
# Using resizeWindow() 
cv2.resizeWindow("test image", 1920, 1080) 
  
# Displaying the image 
cv2.imshow("test image", img) 

one.video_capture.release()
cv2.waitKey(0)
cv2.destroyAllWindows()

#flags FAST_CHECK -> False FAST_CHECK + NORMALIZE -> False  None -> True FAST_CHECK + NORMALIZE + THRESH 
now = dt.datetime.now()
timestamp = util.getSeconds(now)
ret, imgpoints = one.extractCorners(img= img, output_dir= 'test/', find_flags=  cv2.CALIB_CB_ADAPTIVE_THRESH + cv2.CALIB_CB_NORMALIZE_IMAGE + cv2.CALIB_CB_FAST_CHECK)
now = dt.datetime.now()
t2 = util.getSeconds(now)
print(f"all flags time: {(t2 - timestamp)}")
print(ret)

now = dt.datetime.now()
timestamp = util.getSeconds(now)
#print(timestamp)
ret, imgpoints = one.extractCorners(img= img, output_dir= 'test/', find_flags=  None)
now = dt.datetime.now()
t2 = util.getSeconds(now)
#print(t2)
print(f"no flags time: {(t2 - timestamp)}")
print(ret)

##best one!
now = dt.datetime.now()
timestamp = util.getSeconds(now)
#print(timestamp)
ret, imgpoints = one.extractCorners(img= img, output_dir= 'test/', find_flags=  cv2.CALIB_CB_ADAPTIVE_THRESH + cv2.CALIB_CB_FAST_CHECK)
now = dt.datetime.now()
t2 = util.getSeconds(now)
#print(t2)
print(f"no norm flag time: {(t2 - timestamp)}")
print(ret)

now = dt.datetime.now()
timestamp = util.getSeconds(now)
#print(timestamp)
ret, imgpoints = one.extractCorners(img= img, output_dir= 'test/', find_flags= cv2.CALIB_CB_FAST_CHECK)
now = dt.datetime.now()
t2 = util.getSeconds(now)
#print(t2)
print(f"only fast flag time: {(t2 - timestamp)}")
print(ret)


In [2]:
#COMPUTING INTRINSIC PARAMETERS TEST
import numpy as np
import cv2
import re
import datetime as dt
import lib.util as util
import lib.Calibration as cal
from tqdm import tqdm

camera = 'out6F'
input_dir = f'samples/{camera}'
all_chessboard_sizes = [(5, 7), (5, 7), (5, 7), (5, 7), (6, 9), (6, 9), (5, 7), (6, 9), (6, 9), (0, 0), (6, 9), (5, 7),
                        (5, 7)]
chessboard_size = all_chessboard_sizes[int(re.search('\d',camera)[0]) - 1]

CHESS_WIDTH = chessboard_size[0]
CHESS_HEIGHT = chessboard_size[1]


img_list = util.loadImagesBatch(input_dir)
img_size =  ((img_list[0]).shape[1], (img_list[0]).shape[0]) #width and height
imgpoints = []
objpoints = []
print(img_size)
objp = np.zeros((CHESS_WIDTH * CHESS_HEIGHT, 3), np.float32)
objp[:, :2] = np.mgrid[0:CHESS_WIDTH, 0:CHESS_HEIGHT].T.reshape(-1, 2)

for img in tqdm(img_list):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    ret, points = cv2.findChessboardCorners(gray,(CHESS_WIDTH, CHESS_HEIGHT),None, cv2.CALIB_CB_FAST_CHECK + cv2.CALIB_CB_ADAPTIVE_THRESH)
    if ret:
        objpoints.append(objp)
        imgpoints.append(points)

print(f'first imgpoints: {imgpoints[0]}')
#no subpixel cases

    #tc std.
tc = (cv2.TERM_CRITERIA_EPS, 0.005)
print(f'tcstd{tc}')
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, img_size , None, tc)
json_camera_matrix = {
        'ret' : ret,
        'mtx' : mtx.tolist(),
        'dist': dist.tolist(),
        'rvecs' : [rvecs[0].tolist(), rvecs[1].tolist()],
        'tvecs' : [tvecs[0].tolist(), tvecs[1].tolist()]
}
util.saveToJSON(json_camera_matrix, f'{camera}std')
    #tc high accuracy
tc = (cv2.TERM_CRITERIA_EPS, 0.00001)
print(f'tchigh{tc}')
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, img_size , None, tc)
json_camera_matrix = {
        'ret' : ret,
        'mtx' : mtx.tolist(),
        'dist': dist.tolist(),
        'rvecs' : [rvecs[0].tolist(), rvecs[1].tolist()],
        'tvecs' : [tvecs[0].tolist(), tvecs[1].tolist()]
}
util.saveToJSON(json_camera_matrix, f'{camera}high_acc')
    #tc high accuracy and iteration
tc = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 0.005, 50)
print(f'tccombine{tc}')
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, img_size , None, tc)
json_camera_matrix = {
        'ret' : ret,
        'mtx' : mtx.tolist(),
        'dist': dist.tolist(),
        'rvecs' : [rvecs[0].tolist(), rvecs[1].tolist()],
        'tvecs' : [tvecs[0].tolist(), tvecs[1].tolist()]
}
util.saveToJSON(json_camera_matrix, f'{camera}iter')

#subpixel refinement



list: ['chessboard17.jpg', 'chessboard37.jpg', 'chessboard46.jpg', 'chessboard26.jpg', 'chessboard25.jpg', 'chessboard34.jpg', 'chessboard43.jpg', 'chessboard39.jpg', 'chessboard8.jpg', 'chessboard0.jpg', 'chessboard32.jpg', 'chessboard50.jpg', 'chessboard30.jpg', 'chessboard44.jpg', 'chessboard15.jpg', 'chessboard10.jpg', 'chessboard5.jpg', 'chessboard47.jpg', 'chessboard31.jpg', 'chessboard40.jpg', 'chessboard42.jpg', 'chessboard29.jpg', 'chessboard33.jpg', 'chessboard16.jpg', 'chessboard41.jpg', 'chessboard7.jpg', 'chessboard24.jpg', 'chessboard2.jpg', 'chessboard21.jpg', 'chessboard1.jpg', 'chessboard38.jpg', 'chessboard13.jpg', 'chessboard11.jpg', 'chessboard18.jpg', 'chessboard22.jpg', 'chessboard48.jpg', 'chessboard4.jpg', 'chessboard3.jpg', 'chessboard9.jpg', 'chessboard27.jpg', 'chessboard6.jpg', 'chessboard20.jpg', 'chessboard45.jpg', 'chessboard12.jpg', 'chessboard28.jpg', 'chessboard23.jpg', 'chessboard35.jpg', 'chessboard49.jpg', 'chessboard19.jpg', 'chessboard36.jpg', 'ch

100%|██████████| 51/51 [01:12<00:00,  1.43s/it]


first imgpoints: [[[1428.7655   283.13858]]

 [[1498.3049   276.12943]]

 [[1569.8535   272.19763]]

 [[1641.8898   266.46866]]

 [[1717.5      261.5    ]]

 [[1794.       257.     ]]

 [[1422.0472   353.78775]]

 [[1492.0867   347.8353 ]]

 [[1564.6211   341.3745 ]]

 [[1638.3333   337.55273]]

 [[1712.5631   333.20157]]

 [[1790.194    329.6898 ]]

 [[1417.9502   423.38696]]

 [[1487.9662   419.07037]]

 [[1559.3679   415.41776]]

 [[1636.8497   411.10345]]

 [[1709.7196   407.51184]]

 [[1786.2627   403.67337]]

 [[1413.5361   496.98953]]

 [[1483.6548   491.72885]]

 [[1555.7334   488.3309 ]]

 [[1630.       486.     ]]

 [[1705.6099   481.4978 ]]

 [[1785.222    478.7317 ]]

 [[1408.14     570.60645]]

 [[1480.5      566.5    ]]

 [[1552.08     564.2846 ]]

 [[1626.8676   560.69476]]

 [[1703.4434   558.9094 ]]

 [[1781.5      557.     ]]

 [[1405.1547   644.1863 ]]

 [[1477.5      642.5    ]]

 [[1548.6377   639.459  ]]

 [[1624.9247   636.2973 ]]

 [[1701.       639.     ]]

 [[

True

In [5]:
#UNDISTORTION TEST
import numpy as np
import cv2
import os
import datetime as dt
import lib.util as util
import lib.Calibration as cal

camera = 'out6F'
image = 'chessboard10'

und_dir = f'undistorted/{camera}'
os.makedirs(und_dir, exist_ok=True)

# Remove all files in the directory
for file in os.listdir(und_dir):
    os.remove(os.path.join(und_dir, file))

filepath = f'samples/{camera}/{image}.jpg'
img = cv2.imread(filename=filepath)

#showing original image
util.showImage(img, 'original')

#refining camera matrix
path = '6Fcorners.json'
dict = util.LoadJSON(path)
h, w = img.shape[:2]
#standard values, taken from the json
std_mtx = np.array(dict['mtx'])
std_dist = np.array(dict['dist'])
print(f"numpy matrix: {std_mtx}")
new_mtx, roi = cv2.getOptimalNewCameraMatrix(std_mtx, std_dist, (w,h), 1, (w,h))

x, y, w, h = roi

#undistort the image, corrected with the new computed camera matrix
new_dist = np.array([])
und_img = cv2.undistort(src=img, cameraMatrix= std_mtx, dst= new_dist ,distCoeffs= std_dist, newCameraMatrix= new_mtx)
util.showImage(und_img, 'undistorted - new camera matrix - no crop')
cv2.imwrite(f'{und_dir}/{camera}_new_mtx_no.jpg',und_img)
#print((np.size(np.array(und_img),0),np.size(np.array(und_img),1)))
# crop
crop_und_img = und_img[y:y+h, x:x+w]
util.showImage(crop_und_img, 'undistorted - new camera matrix - cropped')
cv2.imwrite(f'{und_dir}/{camera}_new_mtx.jpg', crop_und_img)
#no new camera matrix
und_img = cv2.undistort(src=img, cameraMatrix= std_mtx, dst= new_dist ,distCoeffs= std_dist)
util.showImage(und_img, 'undistorted - standard camera matrix - no crop')
cv2.imwrite(f'{und_dir}/{camera}_std_mtx.jpg',und_img)
# crop 
# no_crop_und_img = und_img[y:y+h, x:x+w]
#util.showImage(und_img, 'undistorted - standard camera matrix - cropped')


numpy matrix: [[5.30060886e+03 0.00000000e+00 1.93584864e+03]
 [0.00000000e+00 5.37918766e+03 1.06242499e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]


True

In [2]:
#image ordered calibration tests 
import numpy as np
import cv2
import re
import datetime as dt
import lib.util as util
import lib.Calibration as cal
from tqdm import tqdm

camera = 'out2F'
input_dir = f'samples/{camera}'
all_chessboard_sizes = [(5, 7), (5, 7), (5, 7), (5, 7), (6, 9), (6, 9), (5, 7), (6, 9), (6, 9), (0, 0), (6, 9), (5, 7),
                        (5, 7)]
chessboard_size = all_chessboard_sizes[int(re.search('\d',camera)[0]) - 1]

CHESS_WIDTH = chessboard_size[0]
CHESS_HEIGHT = chessboard_size[1]



img_list = util.loadImagesBatch(input_dir)
img_list_sorted = util.loadImagesBatch(input_dir, True)

img_size =  ((img_list[0]).shape[1], (img_list[0]).shape[0]) #width and height
imgpoints = []
objpoints = []
print(img_size)
objp = np.zeros((CHESS_WIDTH * CHESS_HEIGHT, 3), np.float32)
objp[:, :2] = np.mgrid[0:CHESS_WIDTH, 0:CHESS_HEIGHT].T.reshape(-1, 2)
tc = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 0.005, 50)


for img in tqdm(img_list):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    ret, points = cv2.findChessboardCorners(gray,(CHESS_WIDTH, CHESS_HEIGHT),None, cv2.CALIB_CB_FAST_CHECK + cv2.CALIB_CB_ADAPTIVE_THRESH)
    if ret:
        #print('found')
        objpoints.append(objp)
        imgpoints.append(points)

print(f'first imgpoints: {imgpoints[0][0]}')
print(len(imgpoints))
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, img_size , None, tc)
json_camera_matrix = {
        'ret' : ret,
        'mtx' : mtx.tolist(),
        'dist': dist.tolist(),
        'rvecs' : [rvecs[0].tolist(), rvecs[1].tolist()],
        'tvecs' : [tvecs[0].tolist(), tvecs[1].tolist()]
}
util.saveToJSON(json_camera_matrix, f'{camera}std_fetching')

imgpoints = []
objpoints = []

for img in tqdm(img_list_sorted):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    ret, points = cv2.findChessboardCorners(gray,(CHESS_WIDTH, CHESS_HEIGHT),None, cv2.CALIB_CB_FAST_CHECK + cv2.CALIB_CB_ADAPTIVE_THRESH)
    if ret:
        objpoints.append(objp)
        imgpoints.append(points)

print(f'first imgpoints: {imgpoints[0][0]}')
print(len(imgpoints))
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, img_size , None, tc)
ordered_json_camera_matrix = {
        'ret' : ret,
        'mtx' : mtx.tolist(),
        'dist': dist.tolist(),
        'rvecs' : [rvecs[0].tolist(), rvecs[1].tolist()],
        'tvecs' : [tvecs[0].tolist(), tvecs[1].tolist()]
}
util.saveToJSON(ordered_json_camera_matrix, f'{camera}sorted_fetching')




list: ['chessboard17.jpg', 'chessboard37.jpg', 'chessboard46.jpg', 'chessboard26.jpg', 'chessboard25.jpg', 'chessboard53.jpg', 'chessboard34.jpg', 'chessboard52.jpg', 'chessboard43.jpg', 'chessboard39.jpg', 'chessboard8.jpg', 'chessboard0.jpg', 'chessboard32.jpg', 'chessboard50.jpg', 'chessboard30.jpg', 'chessboard44.jpg', 'chessboard15.jpg', 'chessboard10.jpg', 'chessboard5.jpg', 'chessboard59.jpg', 'chessboard47.jpg', 'chessboard31.jpg', 'chessboard40.jpg', 'chessboard42.jpg', 'chessboard29.jpg', 'chessboard54.jpg', 'chessboard33.jpg', 'chessboard16.jpg', 'chessboard41.jpg', 'chessboard7.jpg', 'chessboard24.jpg', 'chessboard57.jpg', 'chessboard2.jpg', 'chessboard21.jpg', 'chessboard1.jpg', 'chessboard56.jpg', 'chessboard38.jpg', 'chessboard13.jpg', 'chessboard11.jpg', 'chessboard18.jpg', 'chessboard22.jpg', 'chessboard48.jpg', 'chessboard4.jpg', 'chessboard3.jpg', 'chessboard9.jpg', 'chessboard58.jpg', 'chessboard27.jpg', 'chessboard6.jpg', 'chessboard20.jpg', 'chessboard45.jpg', 'ch

100%|██████████| 60/60 [00:55<00:00,  1.08it/s]


first imgpoints: [[[2511.2573 1429.4196]]

 [[2598.417  1436.1726]]

 [[2683.5823 1443.8806]]

 [[2770.335  1450.5688]]

 [[2856.677  1455.0978]]

 [[2508.044  1511.5557]]

 [[2592.4006 1518.7101]]

 [[2677.578  1525.2919]]

 [[2761.9016 1533.4159]]

 [[2847.2607 1539.0739]]

 [[2503.0168 1589.766 ]]

 [[2587.337  1596.8707]]

 [[2669.858  1603.93  ]]

 [[2753.4512 1611.6711]]

 [[2836.2014 1620.0504]]

 [[2497.8682 1665.489 ]]

 [[2580.1475 1672.1979]]

 [[2661.5596 1680.0149]]

 [[2743.9783 1687.0309]]

 [[2826.105  1694.951 ]]

 [[2492.052  1738.472 ]]

 [[2572.7935 1745.3141]]

 [[2653.5513 1752.1088]]

 [[2733.3428 1760.4625]]

 [[2814.617  1767.7542]]

 [[2486.004  1807.653 ]]

 [[2565.0032 1815.362 ]]

 [[2644.5217 1822.934 ]]

 [[2723.3694 1829.8905]]

 [[2802.4587 1837.0004]]

 [[2479.1455 1873.6735]]

 [[2557.095  1881.2943]]

 [[2635.3777 1889.1616]]

 [[2711.7727 1897.1212]]

 [[2790.2825 1903.6965]]]
60


100%|██████████| 60/60 [00:55<00:00,  1.09it/s]


first imgpoints: [[1669.6437 1672.8748]]
60


True

In [17]:
def progressBar (num:int):
    star = '*'
    slash = '-'
    bar = '['
    if num >= 20:
        print('[********************]')
    for it in range(num):
        bar = bar + star
    for it in range(20-num):
        bar = bar + slash
    bar = bar + ']'
    return bar

def showProgressBar(iteration:int, condition:int) -> None:
    if(iteration >= condition):
        print(progressBar(20))
    else:
        print(progressBar(int((iteration) / (condition / 20))))
 
i = 0
while i < 100:
    showProgressBar(i, 100)
    i += 10
    

[--------------------]
[**------------------]
[****----------------]
[******--------------]
[********------------]
[**********----------]
[************--------]
[**************------]
[****************----]
[******************--]


In [1]:
#solvePnP TEST
import numpy as np
import cv2
import re
import datetime as dt
import lib.util as util
import lib.Calibration as cal
from tqdm import tqdm

def computeReProjError(objpoints, imgpoints, mtx, dist, rvecs, tvecs):
    """
    method for computing multiple reprojeciton errors.
    It returns the average value of the reprojeciton errors, different from the openCv calibrateCamera ret value(which is RMSE)
        - objpoints: list of object points in the 3D camera space
        - imgpoints: list of image points in the 2D camera plane
        - mtx: camera matrix (3x3)
        - dist: distorsion values of the camera
        - rvecs: list of rotation vectors 
        - tvecs: list of translation vectors
    """
    mean_error = 0
    for i in range(np.shape(objpoints)[0]):
        imgpoints2, _ = cv2.projectPoints(objpoints[i], rvecs[i], tvecs[i], mtx, dist)
        error = cv2.norm(imgpoints[i], imgpoints2, cv2.NORM_L2)/len(imgpoints2)
        mean_error += error/ (np.shape(objpoints)[0])
    return mean_error

def computeMultiplePnP(objpoints, imgpoints, mtx, dist, flags=cv2.SOLVEPNP_ITERATIVE):
    tvecs = []
    rvecs = []
    for i in range(np.shape(objpoints)[0]):
        r, rvec, tvec = cv2.solvePnP(objpoints[i], imgpoints[i], mtx, dist, flags)
        rvecs.append(rvec)
        tvecs.append(tvec)
    return (rvecs, tvecs)

#Refine case of solvePnP
def computeMultipleRefinePnP(objpoints, imgpoints, mtx, dist, rvecs, tvecs):
    final_tvecs = []
    final_rvecs = []
    for i in range(np.shape(objpoints)[0]):
        print(rvecs[i])
        rvec, tvec = cv2.solvePnPRefineLM(objpoints[i], imgpoints[i], mtx, dist, rvecs[i], tvecs[i] ) 
        final_rvecs.append(rvec)
        final_tvecs.append(tvec)
    return (final_rvecs, final_tvecs)

camera = 'out2F'
input_dir = f'samples/{camera}'
all_chessboard_sizes = [(5, 7), (5, 7), (5, 7), (5, 7), (6, 9), (6, 9), (5, 7), (6, 9), (6, 9), (0, 0), (6, 9), (5, 7),
                        (5, 7)]
chessboard_size = all_chessboard_sizes[int(re.search('\d',camera)[0]) - 1]

CHESS_WIDTH = chessboard_size[0]
CHESS_HEIGHT = chessboard_size[1]

img_list = util.loadImagesBatch(input_dir)

img_size =  ((img_list[0]).shape[1], (img_list[0]).shape[0]) #width and height
imgpoints = []
objpoints = []
print(img_size)
objp = np.zeros((CHESS_WIDTH * CHESS_HEIGHT, 3), np.float32)
objp[:, :2] = np.mgrid[0:CHESS_WIDTH, 0:CHESS_HEIGHT].T.reshape(-1, 2)
tc = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 0.005, 50)


for img in tqdm(img_list):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    ret, points = cv2.findChessboardCorners(gray,(CHESS_WIDTH, CHESS_HEIGHT),None, cv2.CALIB_CB_FAST_CHECK + cv2.CALIB_CB_ADAPTIVE_THRESH)
    if ret:
        #print('found')
        objpoints.append(objp)
        imgpoints.append(points)
objpoints = np.array(objpoints)
imgpoints = np.array(imgpoints)

print(f'img: {np.shape(imgpoints)}\nobj: {np.shape(objpoints)}')

#Using std. calibrateCamera method as a base value for comparison
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, img_size , None, tc)
#print(f"ret:{ret}\nmtx:{mtx}\ndist:{dist}\nrvecs:{rvecs}\ntvecs:{tvecs}")
print(f"ret:{ret}")
print(f"rvecs0:{rvecs[0]}\ntvecs0:{tvecs[0]}")
print(f"rvecs:{rvecs}")


#using solvePnP (Levenberg-Marquardt optimization), same as calibrateCamera
pnp_rvecs, pnp_tvecs = computeMultiplePnP(objpoints, imgpoints, mtx, dist)
pnp_tvecs = np.array(pnp_tvecs)
pnp_rvecs = np.array(pnp_rvecs)
error = computeReProjError(objpoints,imgpoints, mtx, dist, pnp_rvecs, pnp_tvecs)
print(f"tvec1:{pnp_tvecs[0]}")
print(f"std. result: {error}")

#using solvePnP, coplanar object points("Infinitesimal Plane-Based Pose Estimation")
pnp_rvecs, pnp_tvecs = computeMultiplePnP(objpoints, imgpoints, mtx, dist, flags= cv2.SOLVEPNP_IPPE)
pnp_tvecs = np.array(pnp_tvecs)
pnp_rvecs = np.array(pnp_rvecs)
error = computeReProjError(objpoints,imgpoints, mtx, dist, pnp_rvecs, pnp_tvecs)
print(f"tvec2:{pnp_tvecs[0]}")
print(f"ippe. result: {error}")


###
#using "pose refinement" methods, as suggested from openCv
###

#solvePnPRefineLM(), similar to the std. method, doesn't change the result significantly

refined_rvecs, refined_tvecs = computeMultipleRefinePnP(objpoints, imgpoints, mtx, dist, rvecs, tvecs ) 
print(f"refined_tvec: {refined_tvecs[0]}\nrefined_rvec: {refined_rvecs[0]}")
refined_tvecs = np.array(refined_tvecs)
refined_rvecs = np.array(refined_rvecs)
error = computeReProjError(objpoints,imgpoints, mtx, dist, refined_rvecs, refined_tvecs)
print(f"refinement. result: {error}")
#solvePnPRefineVVS(), similar to the previous

# VVS_rvec, VVS_tvec = cv2.solvePnPRefineVVS(objpoints[0], imgpoints[0], mtx, dist, rvecs[0], tvecs[0] )
# print(f"VVS_tvec: {VVS_tvec}\nrefined_rvec: {VVS_rvec}")

json_camera_matrix = {
        'ret' : ret,
        'mtx' : mtx.tolist(),
        'dist': dist.tolist(),
        'rvecs' : pnp_rvecs.tolist(),
        'tvecs' : pnp_tvecs.tolist()
}



list: ['chessboard17.jpg', 'chessboard37.jpg', 'chessboard46.jpg', 'chessboard26.jpg', 'chessboard25.jpg', 'chessboard53.jpg', 'chessboard34.jpg', 'chessboard52.jpg', 'chessboard43.jpg', 'chessboard39.jpg', 'chessboard8.jpg', 'chessboard0.jpg', 'chessboard32.jpg', 'chessboard50.jpg', 'chessboard30.jpg', 'chessboard44.jpg', 'chessboard15.jpg', 'chessboard10.jpg', 'chessboard5.jpg', 'chessboard59.jpg', 'chessboard47.jpg', 'chessboard31.jpg', 'chessboard40.jpg', 'chessboard42.jpg', 'chessboard29.jpg', 'chessboard54.jpg', 'chessboard33.jpg', 'chessboard16.jpg', 'chessboard41.jpg', 'chessboard7.jpg', 'chessboard24.jpg', 'chessboard57.jpg', 'chessboard2.jpg', 'chessboard21.jpg', 'chessboard1.jpg', 'chessboard56.jpg', 'chessboard38.jpg', 'chessboard13.jpg', 'chessboard11.jpg', 'chessboard18.jpg', 'chessboard22.jpg', 'chessboard48.jpg', 'chessboard4.jpg', 'chessboard3.jpg', 'chessboard9.jpg', 'chessboard58.jpg', 'chessboard27.jpg', 'chessboard6.jpg', 'chessboard20.jpg', 'chessboard45.jpg', 'ch

100%|██████████| 60/60 [01:06<00:00,  1.11s/it]


img: (60, 35, 1, 2)
obj: (60, 35, 3)
ret:1.8953734094668482
rvecs0:[[0.24413177]
 [0.39025496]
 [0.00967061]]
tvecs0:[[ 6.20169495]
 [ 2.9160573 ]
 [22.55598272]]
rvecs:(array([[0.24413177],
       [0.39025496],
       [0.00967061]]), array([[ 0.46461075],
       [-0.618278  ],
       [ 3.04072007]]), array([[-0.96404068],
       [-0.56486928],
       [ 2.76771119]]), array([[-0.43030012],
       [-0.47785445],
       [ 2.98037419]]), array([[-0.39741741],
       [-0.48284318],
       [ 2.99735544]]), array([[-0.87171777],
       [-0.65264139],
       [ 2.78781513]]), array([[ 0.06123746],
       [ 0.54413448],
       [-3.04120696]]), array([[-0.8968947 ],
       [-0.62344141],
       [ 2.79450585]]), array([[ 0.56547892],
       [-0.56797312],
       [ 3.05503329]]), array([[-0.17144159],
       [ 0.54250969],
       [-3.06412137]]), array([[-0.16548821],
       [-0.65625747],
       [ 3.04968913]]), array([[-0.32999485],
       [-0.65963717],
       [ 3.02889534]]), array([[-0.560597

In [4]:
import pickle
file = open('../CV-CameraCalibration/camera_parameters/without_crop/out6F.p', 'rb')
structure = pickle.load(file)

print(structure)

{'mtx': array([[5.60753833e+03, 0.00000000e+00, 1.93008510e+03],
       [0.00000000e+00, 5.86090992e+03, 1.07564978e+03],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]]), 'dist': array([[-1.36328788e-01, -8.02697895e+00, -6.14038178e-03,
        -5.46720100e-02,  2.88947300e+01]]), 'new_mtx': array([[4.90031364e+03, 0.00000000e+00, 1.77690136e+03],
       [0.00000000e+00, 4.94937987e+03, 1.06557667e+03],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])}


In [9]:
import numpy as np
import cv2
import re
import datetime as dt
import lib.util as util
import lib.Calibration as cal
from tqdm import tqdm

video_path = 'videos/out1.mp4'
width = 0
height = 0

def callbackButton():
    print('button pressed')

def showImage(img: cv2.typing.MatLike, window_name: str):
    """
    Takes an image and show it in a fixed size window, press a button to close it in the end
        - img: An image to be shown
        - window_name: the name of the window where displaying the image
    """
    # show the original image
    w_name = window_name
    cv2.namedWindow(w_name, cv2.WINDOW_NORMAL)
    cv2.createButton('select_pixel',callbackButton)
    
    # Using resizeWindow() 
    cv2.resizeWindow(w_name, 1920, 1080)
    #cv2.waitKey(0)
    while cv2.waitKey(33) != ord('a'):
        cv2.imshow(w_name, img)
    cv2.destroyWindow(window_name)


one = cal.Calibration(video_path, width, height)
skip = 15
img = []
print(f'starting skip of {skip}')
for i in range(skip):
    ret, img = one.video_capture.read()
    if not ret:
        break

showImage(img,'frame1')




starting skip of 15
